runtime:
  cache_dir: ./.cache/antora

site:
  title: Knative Tutorial(Staging)
  url: http://redhat-developer-docs.github.io/knative-tutorial-staging
  start_page: knative-tutorial::index.adoc

content:
  sources:
    - url: git@github.com:redhat-developer-demos/knative-tutorial.git
      tags: []
      branches: staging
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: knativetutorial
    branch: staging
    minikube-version: v1.14.1
    openshift-version: v4.6
    kubernetes-version: v1.19.0
    knative-version: v0.17.0
    knative-serving-version: v0.17.4
    net-kourier-version: v0.17.2
    knative-eventing-version: v0.17.8
    knative-sources-version: v0.17.7
    kn-client-version: v0.18.0
    kubernetes-cli: kubectl
    release-version: master
    page-pagination: true
    openshift-console-url: https://console-openshift-console.apps.example.com
    etherpad-url: http://example.com
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
