apiVersion: v1
kind: Service
metadata:
  name: fruityvice-proxy
spec:
  selector:
    app: fruityvice-proxy
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruityvice-proxy
spec:
  selector:
    matchLabels:
      app: fruityvice-proxy
  template:
    metadata:
      labels:
        app: fruityvice-proxy
    spec:
      containers:
        - name: fruityvice-proxy
          image: quay.io/rhdevelopers/fruityvice-proxy
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
